### ISSUE TITLE
REST API: `/account/{pubkey}` endpoint

### ISSUE THREAD

**Issue by kaladinlight** [shapeshift/unchained#193]
AC:
- Path `/account/{pubkey}` GET
- Included in BaseAPI interface with Account interface returned to allow for extending the base account type
- Returns balance and pubkey for base account details
- Returns _ for cosmos specific account details
- OpenAPI supporting doc comments

**Comment by mrnerdhair** [comment]
AC question: what's the format of `pubkey` supposed to be here?

**Comment by mrnerdhair** [comment]
I'd like to see us look harder at the concept of an "account" before we build much of an API for communicating about about them on the wire. This is hard problem, since

- Addresses aren't pubkeys, they're pubkey hashes
- Various ecosystems have "native" methods for encoding pubkeys which are
  - similar to their address encodings (`cosmospub1`-prefixed bech32 in cosmos, 65-byte `0x`-prefixed strings in ethereum) but not interchangeable
  - typically incompatible with other ecosystems
- Blockbook misuses the version bytes in BIP32 encoded extended keys (i.e. the `xpub`/`ypub`/`zpub` prefix) to infer UTXO script type, which it shouldn't because
  - distinct BIP32 version bytes aren't always allocated for new script types (as in the case of taproot)
  - a pubkey can be used to receive UTXOs with several different script types, and it's not at all immediately obvious that those should be considered "different accounts"

When we need to use what you're calling "pubkeys" here in chain-adapters, we call them "account specifiers" -- but we completely made up that name and IMO it would be best to keep the whole concept off the wire if possible.

**Comment by kaladinlight** [comment]
The term `pubkey` was just meant as a generic name to represent some public key (address or xpub) that is used to fetch transaction history or account balance information from a backend node or indexer. In this case for cosmos, we are querying by cosmos address.
